site_name: 福建师范大学Wiki
site_url: https://fjnu.nekoark.com/
theme:
  name: material
nav:
  - 主页: index.md
  - 生活指南: 
    - 餐饮: live_eat.md
    - 住宿: live_living.md
    - 交通: live_traffic.md
    - 医疗: live_hospital.md
  - 学习资源: 
    - 学习制度: study_system.md
    - 考试与成绩、体测与保健班: study_exam.md
    - 课程相关: study_choose.md
    - 学业发展: study_improve.md
  - 校园服务: 
    - 学校信息: service_info.md
    - 校园设施: service_facilities.md
    - 行政服务: service_services.md
    - 网络服务: service_network.md
    - 学生组织和学生工作: service_group.md
  - 新生准备: 
    - 入学准备: new_before.md
    - 军训指南: new_military_training.md
    - 校园导航: new_safari.md
    - 联系方式: new_chat.md
  - 复习资料: repo.md
  - 关于: about.md
extra_css:
  - stylesheets/extra.css
extra:
  include:
    - CNAME
copyright: 'Copyright &copy; 2025 FJNU-Wiki. All Rights Reserved.'